### ISSUE TITLE
Vue 2 is still supported?

### ISSUE THREAD

**Issue by eduflm** [prazdevs/pinia-plugin-persistedstate#18]
Hello!

I need to persist in my pinia state. I have installed this plugin but when starting I am getting this error:

```
vue-composition-api.mjs?d80b:34 Uncaught Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
    at assert (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:88:15)
    at getVueConstructor (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:369:9)
    at eval (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:287:42)
    at withCurrentInstanceTrackingDisabled (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:401:9)
    at new EffectScope (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:286:9)
    at effectScope (webpack-internal:///../../shared/node_modules/@vue/composition-api/dist/vue-composition-api.mjs:309:12)
    at createPinia (webpack-internal:///../../shared/node_modules/pinia/dist/pinia.esm-bundler.js:887:79)
    at eval (webpack-internal:///../../shared/src/pinia/index.js:10:70)
    at Module.../../shared/src/pinia/index.js (app.js:1761:1)
    at __webpack_require__ (app.js:854:30)
```

My code is like this:

```javascript
import { createPinia, PiniaPlugin } from 'pinia'
import Vue from 'vue'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
Vue.use(PiniaPlugin)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

export { pinia }
```

I'm currently using Vue2, pinia version 2.0.0-rc.6 and pinia-plugin-persistedstate version 1.2.1.

Could someone help me get this to work in Vue2? thanks in advance

**Comment by prazdevs** [comment]
Heya :) Yup, as Pinia still works on Vue2, this plugin does too! 
You may want to upgrade your pinia version to the official release (non RC), latest being 2.0.11

I managed to have a perfectly working Vue2 + Pinia + PersistedState using:
- `@vue/composition-api@1.4.6` 
- `pinia@2.0.11`
- `pinia-plugin-persistedstate@1.2.1`
- `vue@2.6.14`

Here's my `main.js` file.
```js
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'
import { createPinia, PiniaVuePlugin } from 'pinia'
import PersistedState from 'pinia-plugin-persistedstate'

import App from './App.vue'

Vue.config.productionTip = false

Vue.use(VueCompositionApi)
Vue.use(PiniaVuePlugin)

const pinia = createPinia().use(PersistedState)

new Vue({
  render: h => h(App),
  pinia
}).$mount('#app')
```
Then defined some stores and used them in composition-api's setup as usual.

The problem you have isn't due to the plugin but more because of how you added Pinia. Hopefully this helps. Let me know if you're still having issues.

**Comment by eduflm** [comment]
You were right! The Pinia version was the problem. I updated and now it is working normally.

Thank you for your help :)
