### ISSUE TITLE
A composable that requires access to the Nuxt instance was called outside of a plugin

### ISSUE THREAD

**Issue by mudoo** [prazdevs/pinia-plugin-persistedstate#211]
### Describe the bug

```
Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.
    at Module.useNuxtApp (E:\web\feature\node_modules\nuxt\dist\app\nuxt.js:225:13)
    at Module.useRequestEvent (E:\web\feature\node_modules\nuxt\dist\app\composables\ssr.js:16:58)
    at readRawCookies (E:\web\feature\node_modules\nuxt\dist\app\composables\cookie.js:53:62)
    at Module.useCookie (E:\web\feature\node_modules\nuxt\dist\app\composables\cookie.js:23:19)
    at Object.setItem (E:\web\feature\node_modules\@pinia-plugin-persistedstate\nuxt\dist\runtime\storages.mjs:13:27)
    at persistState (file:///E:/News/web/feature/node_modules/pinia-plugin-persistedstate/dist/index.mjs:51:13)
    at store.$subscribe.detached (file:///E:/News/web/feature/node_modules/pinia-plugin-persistedstate/dist/index.mjs:113:11)
    at file:///E:/News/web/feature/node_modules/pinia/dist/pinia.mjs:1406:21
    at callWithErrorHandling (E:\web\feature\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:18)
    at callWithAsyncErrorHandling (E:\web\feature\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:164:17)
```

### Reproduction

persist: [{  debug: true  }]

### System Info

```Shell
window10
node 16.20.0
nuxt 3.5.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mudoo** [comment]
server side is not working.

**Comment by mudoo** [comment]
is nuxt3 context bug, not this plugin problem.

**Comment by zllvm** [comment]
It does it seem like it is a nuxt3 bug, but intended behavior. Could it be fixed by wrapping useCookie with callWithNuxt in this module?

**Comment by dasph** [comment]
I've managed to solve this problem by manually defining a nuxt `plugin` where I would call `$pinia.use(createPersistedState(...))` (instead of adding `pinia-plugin-persistedstate/nuxt` to `modules` inside of `nuxt.config.ts`

In my case the error was thrown because of `runWithContext(...)` that's called when you add this plugin trough `nuxt.config`.

**Comment by prazdevs** [comment]
i will try to use the `callWithNuxt` thing and see what happens
