### ISSUE TITLE
Cannot start nuxt after adding pinia-plugin-persistedstate/nuxt

### ISSUE THREAD

**Issue by takburger-ap** [prazdevs/pinia-plugin-persistedstate#267]
### Describe the bug

On a fresh install, package.json :
```json
"devDependencies": {
    "@pinia-plugin-persistedstate/nuxt": "^1.2.0",
    "@pinia/nuxt": "^0.5.1",
    "nuxt": "^3.9.0",
    "vue": "^3.4.3",
    "vue-router": "^4.2.5"
  }
  ```
  running dev :
  ```
  ERROR  Cannot start nuxt:  Nuxt module should be a function: pinia-plugin-persistedstate/nuxt

  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.9.0/node_modules/@nuxt/kit/dist/index.mjs:2498:11)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.9.0/node_modules/@nuxt/kit/dist/index.mjs:2437:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.9.0_vite@5.0.10/node_modules/nuxt/dist/index.mjs:3822:7)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:253:5)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)
  at async NuxtDevServer.init (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev2.mjs:180:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/dev-child.mjs:101:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)
  ```
  
  And the nuxt.config.ts:
  ```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@pinia/nuxt", "pinia-plugin-persistedstate/nuxt"],
});
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wxd3dt?file=nuxt.config.ts

### System Info

```Shell
tested on :
- osx, pnpm & bun
- stackblitz pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by takburger-ap** [comment]
problem was between the chair and the keyboard : forgot the @ in the module declaration.
