### ISSUE TITLE
Unable to use Nuxt with SSR and cookies

### ISSUE THREAD

**Issue by jeanmatthieud** [prazdevs/pinia-plugin-persistedstate#361]
### Are you using Nuxt?

- [X] Check this box if you encountered the issue using Nuxt and the included module.

### Describe the bug

I have a Nuxt project, with pinia + pinia-plugin-persistedstate
I want to be able to use the cookies with SSR.

Pinia is used to store the auth token of the user, and refresh it if required.
I'm using the strore in a custom Nuxt plugin.
It works fine on the client side.
However, I realized that I have an issue if the server side tries to update the cookie through the Pinia store (eg. the new token is retrieve during SSR, and should be stored to the cookie to be transmitted to the client side).

Is it even possible?
I have the following issue when I try to update the store during SSR:

```
[1:04:47 PM]  ERROR  [pinia-plugin-persistedstate] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.

  at Module.useNuxtApp (node_modules/nuxt/dist/app/nuxt.js:251:13)
  at Module.useRequestEvent (node_modules/nuxt/dist/app/composables/ssr.js:11:58)
  at readRawCookies (node_modules/nuxt/dist/app/composables/cookie.js:144:101)
  at Module.useCookie (node_modules/nuxt/dist/app/composables/cookie.js:29:19)
  at Object.setItem (node_modules/pinia-plugin-persistedstate/dist/nuxt/runtime/storages.js:13:52)
  at persistState (node_modules/pinia-plugin-persistedstate/dist/nuxt/runtime/core.js:42:13)
  at store.$subscribe.detached (node_modules/pinia-plugin-persistedstate/dist/nuxt/runtime/core.js:73:29)
  at node_modules/pinia/dist/pinia.mjs:1450:21
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:19)
  at callWithAsyncErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:207:17)
```

It is quite hard to write a reproduction, and it took me a lot of time to find the issue.

### Reproduction

https://stackblitz.com/edit/nuxt-pinia-perstitedstate

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 9.23 GB / 15.52 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.9.1 - /workspaces/[project]/node_modules/.bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prazdevs** [comment]
I see a couple of potential issues/solutions.

Calling the store at the very root of your plugin makes it so the plugin might not be initialised yet (see https://github.com/prazdevs/pinia-plugin-persistedstate/issues/352), the store itself works because of how pinia can work outside of a Vue instance, but it will defer plugin initialisations.

You can try calling `useAuthStore` in deeper scopes instead of at the root, this will defer the moment the store is retrieved, and may make it so the plugin is properly initialised.

For example : 
```ts
async function signInWithToken(newToken: string) {
    // call composable here, I dont think there needs to be a `runWithContext` or such
    const authStore = useAuthStore()
    try {
      authStore.token = newToken;
      await refreshUser();
    } catch (e) {
      authStore.token = undefined;
      authStore.refreshToken = undefined;
    }
  }
```

This _should_ make it work. 

Next version will also expose an explicit name for this plugin (originally called `pinia-plugin-persistedstate`) so you can also try adding `dependsOn: ['pinia-plugin-persistedstate']` on your Nuxt plugin config, but I'm not sure this will really solve the issue.

**Comment by jeanmatthieud** [comment]
Hi,
Thanks for your response.
I already tried to use the store directly in the functions, but I still get the same error.
I'm not sure how I can use the 'dependsOn', as this code is not in a plugin.

When does Pinia try to restore the cookies?

**Comment by prazdevs** [comment]
I will need a more complete reproduction to investigate, cause i cannot reproduce the error with what you sent in the original message.
Pinia restores cookies **when the pinia plugin is initialised** which only happens in Vue context.

**Comment by stephenjason89** [comment]
@jeanmatthieud I have fixed this a long time ago. Pr was not merged. Have a look at #99
And https://github.com/prazdevs/pinia-plugin-persistedstate/issues/97#issuecomment-1206478814

**Comment by jeanmatthieud** [comment]
> I also having this issue, the only way it triggers the error is when the user is getting redirect back from Google auth... The issue doesn't trigger in any other navigation or situation for me...

When you're coming from Google Auth, the site uses SSR (inconsistencies between server cookies and browser cookies). When you're only navigating on your site (without full refresh), the cookies are only set on the client side (browser).

**Comment by aparod** [comment]
I'm also running into this issue in my Nuxt 3 app when trying to use a Pinia store from route middleware.

1. My Pinia store is configured with `persist: { storage: piniaPluginPersistedstate.cookies() }`
2. My route middleware looks like this (simplified to reproduce the problem):

```typescript
export default defineNuxtRouteMiddleware((to, from) => {
  const loggedIn = false

  if (!loggedIn) {
    const nuxtApp = useNuxtApp()
    const alertStore = useAlertStore(nuxtApp.$pinia)

    alertStore.createAlert('error', 'Please log in to continue.')

    return navigateTo('/')
  }
})
```

When this middleware runs server-side, I get the exact error posted in the original comment.  There is no error when the middleware runs client-side.

**Comment by aparod** [comment]
As a workaround, I figured out that when the code runs server-side I can manually set the cookie Pinia uses rather than working with the store itself.  Then, the Pinia store will read the cookie when the client application loads:

```typescript
const alert = { 'error', 'Please log in to continue.' }

if (import.meta.client) {
  alertStore.createAlert(alert)

  return abortNavigation()
}
else {
  const alertCookie = useCookie('alerts')
  alertCookie.value = JSON.stringify({ alerts: [alert] })

  return navigateTo('/')
}
```

**Comment by mishabbk** [comment]
I also get this error.

If I try to update the state in the ssr context, I get the error: "A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function."
In this case, the old state is taken on the client and I also get an additional error: "Hydration completed but contains mismatches."

I even tried to call store.$persist() manually in ssr context (I know that this should not be done, I was just trying to solve the problem), but this, unfortunately, did not help, I also get the error: "A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function."
